max_pred_length:
  desc: Maximum Number of Periods Predicted
  value: 7
max_encoder_length:
  desc: Maximum Number Periods used as Input
  value: 180
max_epochs:
  desc: Maximum Number of Epochs for fitting
  value: 50
gradient_clip_val:
  desc: Gradient Clip Value provided to pytorch trainer
  value: 0.03
learning_rate:
  desc: Learning Rate used for training
  value: 0.03
hidden_size:
  desc: Number of hidden layers in network
  value: 16
attention_head_size:
  desc: number of attention heads. Set to up to 4 for large datasets
  value: 4
dropout:
  desc: Dropout Rate for Training. Recommended between .1 and .3
  value: 0.25
hidden_continuous_size:
  desc: set to <= hidden_size
  value: 4
reduce_on_plateau_patience:
  desc: reduce learning rate if no improvement in validation loss after x epochs
  value: 8
output_size:
  desc: 7 quantiles by default
  value: 7
transformation:
  desc: Transform for Group Fitter
  value: "softplus"
impute_strategy:
  desc: Impute strategy for missing values. Only used if imputation is used
  value: "median"
n_neighbors:
  desc: Only used in value imputation
  value: 8
weights:
  desc: Only used in value imputation
  value: "distance"
targets:
  desc: Varable(s) to be Predicted
  value: "new_cases_smoothed"
static_reals:
  desc:
  value: ['population','population_density','median_age','aged_65_older','aged_70_older',
          'gdp_per_capita','cardiovasc_death_rate', 'diabetes_prevalence', 'handwashing_facilities',
          'hospital_beds_per_thousand', 'life_expectancy', 'human_development_index', 'extreme_poverty', 'female_smokers','male_smokers']
time_varying_known_reals:
  desc: in reality unknown but could be used for conditional forecasts
  value: ['time_idx','stringency_index', 'new_tests_smoothed','new_vaccinations_smoothed',
          'new_deaths_smoothed']
